name: isentry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gal: ^2.3.0
  http: ^1.2.2
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  mobile_scanner: ^6.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  reactive_button: ^0.0.9
  screenshot: ^3.0.0
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  video_player: ^2.9.2
  avatar_stack: ^1.2.0
  quickalert: ^1.1.0
  flutter_vlc_player: ^7.4.2
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  # iOS is disabled for now
  # ios: true
  image_path: "assets/icons/isentry.png"
  adaptive_icon_background: "#F1F4F9"

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    # - assets/medias/
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Semibold.otf
