name: isentry
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  image_picker: ^0.8.4+4
  gal: ^2.3.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  lucide_icons: ^0.257.0
  reactive_button: ^0.0.9
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.1
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  # iOS is disabled for now
  # ios: true
  image_path: "assets/icons/isentry.png"
  adaptive_icon_background: "#F1F4F9"

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Semibold.otf