name: isentry
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  camera: ^0.11.0+2
  gal: ^2.3.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  lucide_icons: ^0.257.0
  reactive_button: ^0.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  # iOS is disabled for now
  # ios: true
  image_path: "assets/icons/icon_iSentry.png"
  adaptive_icon_background: "#F1F4F9"

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Semibold.otf