name: camera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  rtmp_broadcaster: ^2.2.6
  path_provider: ^2.1.5
  video_player: ^2.9.2
  wakelock_plus: ^1.2.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
